### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/vladimir.divljakovic#1]
Hi @vladimir176989,

Please do the following:
1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by vladimir176989** [comment]
I received this test ticket @valentinacupac

**Comment by valentinajemuovic** [comment]
Thanks, you can now close it @vladimir176989
