### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by vladimir176989** [alptium/vladimir.divljakovic#3]

**Comment by vladimir176989** [comment]
I have done Calculator project @valentinacupac

**Comment by valentinajemuovic** [comment]
@vladimir176989:
1. Please see review comment 2. https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
2. [Style] The indentation (tabs) looks a bit strange for the "try" block, please see https://github.com/alptium/valentina.cupac/blob/master/calculator/src/org/alptium/valentinacupac/samples/calculator/Main.java regarding indentation
3. [Style] There needs to be an empty line after the package, and an empty line after import statements

**Comment by valentinajemuovic** [comment]
Discontinued, closing ticket.
